### ISSUE TITLE
Support rgb and hsl new syntax in CSS Color Level 4

### ISSUE THREAD

**Issue by upsuper** [servo/rust-cssparser#113]
That is, to
* make `rgb` an alias of `rgba`
* make `hsl` an alias of `hsla`
* make alpha channel optional for all functions above
* accept whitespace splited form

https://drafts.csswg.org/css-color-4/#rgb-functions
https://drafts.csswg.org/css-color-4/#the-hsl-notation

**Comment by SimonSapin** [comment]
Do you know what the implementation status of this is in other engines?

**Comment by upsuper** [comment]
Gecko supports the new syntax for these four functions (and I saw test failures in Gecko's test with stylo because of lack of the support of them).

Gecko's implementing bug for this seems to be [bug 1295456](https://bugzilla.mozilla.org/show_bug.cgi?id=1295456) but I don't see an intent to ship for this.

It seems to me that no any other engine is shipping this. That reminds me that we probably should inform the working group that Gecko is shipping it.

**Comment by upsuper** [comment]
In addition to what I've mentioned above, the functions also accept `<number>`s and `<percentage>`s for all components rather than only `<integer>`.

**Comment by manuel-woelker** [comment]
I'd like to tackle this one. Let me know if anyone else is currently working on this.

It look to be relatively straightforward. I'd probably need to update some test cases in color3.json that are now valid.

I'd like to use the test spec cases to add additional test cases:
http://test.csswg.org/suites/css-color-4_dev/nightly-unstable/html/chapter-4.htm

**Comment by SimonSapin** [comment]
Yes, please add new test cases (and modify existing ones as needed) in `color3.json`, and extend `make_color3_hsl.py` as well. It is used like so: `python2 make_color3_hsl.py > color3_hsl.json`.

Feel free to ask here or on `#servo` IRC if you have any question.
