### ISSUE TITLE
`match_ignore_ascii_case` fails to return value after some characters

### ISSUE THREAD

**Issue by canaltinova** [servo/rust-cssparser#126]
Simple test case:
```patch
diff --git a/src/tests.rs b/src/tests.rs
index 8419943..fe19381 100644
--- a/src/tests.rs
+++ b/src/tests.rs
@@ -843,3 +843,21 @@ fn procedural_masquerade_whitespace() {
         _ => panic!("4"),
     }
 }
+
+#[test]
+fn test_length() {
+    match_ignore_ascii_case! { "fo",
+        "bar" => {},
+        value => assert_eq!(value, "fo"),
+    }
+
+    match_ignore_ascii_case! { "foo",
+        "bar" => {},
+        value => assert_eq!(value, "foo"),
+    }
+
+    match_ignore_ascii_case! { "fooo",
+        "bar" => {},
+        value => assert_eq!(value, "fooo"),
+    }
+}
```
In this function, first two `match_ignore_ascii_case` passes but in the third macro, value returns "A". I have the same problem with this macro in https://github.com/servo/servo/pull/15813 But it breaks after 11 characters.

cc @SimonSapin

**Comment by emilio** [comment]
I believe this is intended, `A` is what the macro uses when it knows that it definitely doesn't match, which is when the length of the value passed in is greater than all the patterns.

**Comment by emilio** [comment]
I guess the "fix" here is forbidding pattern bindings? or maybe simon can think of a better solution?

**Comment by canaltinova** [comment]
Ah, now it makes sense why character limits have changed :)
>match_ignore_ascii_case! now supports the full syntax of match expressions, including alternatives pattern | other_pattern, bindings name @ pattern, and guards pattern if condition

After @SimonSapin's note in the PR I thought we can use like this.

**Comment by emilio** [comment]
we can't, but we can fix it I guess. We can `unwrap_or` input, though it'd be (slightly) less efficient.

**Comment by emilio** [comment]
Fix in #127

**Comment by emilio** [comment]
Well, as mentioned there, the fix is quite wallpaper-ish, your tests will all pass with it, but the following will fail with: `assertion failed: `(left == right)` (left: `"fo"`, right: `"Fo"`)`

```rust
#[test]
fn known_not_matching_lowercased() {
    match_ignore_ascii_case! { "Fo",
        "bar" => {},
        value => assert_eq!(value, "Fo"),
    }
}
```

**Comment by SimonSapin** [comment]
As discussed in #127 I’ll make another PR to remove support for match bindings.
