### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by KuoE0** [servo/rust-cssparser#136]
Could you create a new release after this commit (https://github.com/servo/rust-cssparser/commit/19431919deebec7d8dba29d889621b35cf5f10ef)? 

I'm intent to update the cssparser used in servo. It could fix this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1353994) after servo using the cssparser with this commit.

**Comment by SimonSapin** [comment]
Version 0.12.2 is now on crates.io and includes 19431919deebec7d8dba29d889621b35cf5f10ef.
