### ISSUE TITLE
In An+B notation, it should be invalid to have comment between "A" and "n"

### ISSUE THREAD

**Issue by upsuper** [servo/rust-cssparser#138]
Things like `:nth-child(-1/**/n+1)` should be invalid.

It is not clear to me whether the spec matches that.

cc @SimonSapin

**Comment by SimonSapin** [comment]
What is "should" if not according to a spec?

**Comment by upsuper** [comment]
The spec says inserting whitespace there is invalid, so presumably adding comment is invalid as well? I suspect it indicates that `An` should be an unbreakable token?

**Comment by upsuper** [comment]
So, yeah, `An` is a dimension token according to the spec, so it should be unbreakable: https://drafts.csswg.org/css-syntax-3/#the-anb-type

**Comment by SimonSapin** [comment]
Without the comment, `-1n+1` tokenizes as a dimention token with unit `n`, followed by a number token with an explicit plus sign. This matches `<n-dimension> <signed-integer>` in https://drafts.csswg.org/css-syntax/#the-anb-type.

With the comment it becomes an integer token, then an ident token, then an integer token with a plus sign. This does not match that grammar.

**Comment by SimonSapin** [comment]
If I add `"-1/**/n+1", null,` (expecting a parse error) to `src/css-parsing-tests/An+B.json`, unit tests still pass. So is there anything to do here?

**Comment by upsuper** [comment]
Oh, it seems I misunderstood the test result. It is Gecko who's wrong on this.

**Comment by SimonSapin** [comment]
(Gecko was correct according to the Selectors Level 3 definition: `['-'|'+']? INTEGER? {N} [ S* ['-'|'+'] S* INTEGER ]?`, but that bit of grammar was weird of sort-of incompatible with the usual CSS tokenization.)

**Comment by bzbarsky** [comment]
So I'm still a bit confused.

In Gecko, `:nth-child(-1/**/n+1)` does not parse.  In stylo it does.  As far as I can tell per https://drafts.csswg.org/css-syntax/#the-anb-type it should not parse.  @SimonSapin's earlier comments say it doesn't parse, but stylo is very much parsing it.  What's going on, exactly?
