### ISSUE TITLE
:nth-child(-/**/n+2) should parse

### ISSUE THREAD

**Issue by Manishearth** [servo/rust-cssparser#153]
According to [the spec](https://drafts.csswg.org/css-syntax-3/#the-anb-type), spaces are not allowed between `+n` and `-n` in `nth-child`, however it says nothing about comments. Chrome allows this, and with https://bugzilla.mozilla.org/show_bug.cgi?id=1364009, Firefox will too. We should as well.

cc @SimonSapin @dbaron

**Comment by SimonSapin** [comment]
`+/**/n+2` matches `'+'?† n <signed-integer>`, but `-/**/n+2` doesn’t match the grammar.

**Comment by emilio** [comment]
Still is what's accepted by other browsers, isn't it? Worth filing a spec issue I guess.

**Comment by SimonSapin** [comment]
*shrugs*
For once I think this *is* something that only ever happens in test cases.

**Comment by Manishearth** [comment]
Yeah, the comments don't matter as much.

Though gecko has an absurd number of tests for that 😄

**Comment by SimonSapin** [comment]
Closing in favor of https://github.com/w3c/csswg-drafts/pull/1498.
