### ISSUE TITLE
File not found in README

### ISSUE THREAD

**Issue by danger89** [servo/rust-cssparser#166]
Within the README.md you link to a file that doesn't exist anymore within this archive. Probably you want to link to an other file now.

>See [the `ast` module](src/ast.rs) for the data structures.

Kind regards,
Melroy

**Comment by danger89** [comment]
Since this ast module and thus the README.md belongs to a very very old version (tagged as v0.1.1) of the cssparser, you may need to rewrite the readme as well. (atleast the overview section).

**Comment by atouchet** [comment]
This was fixed in #240.
