### ISSUE TITLE
Don't package big-data-url.css and color3_hsl.json

### ISSUE THREAD

**Issue by jdm** [servo/rust-cssparser#169]
They are files that are >100k and trigger the large file error when vendoring in mozilla-central. If we could avoid packaging them, that would be nice.

**Comment by SimonSapin** [comment]
http://doc.crates.io/manifest.html#the-exclude-and-include-fields-optional

**Comment by SimonSapin** [comment]
If we’re removing test files all of `src/css-parsing-tests` should also be removed, even files under 100k.
