### ISSUE TITLE
CSS 2 System colors

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-cssparser#2]
[System colors](http://www.w3.org/TR/css3-color/#css2-system) are deprecated, but what exactly should Servo do with them?
- Not support them at all: treat them as invalid like any other unknown keyword
- Interpret them all like `initial`
- Treat as `white` those that have the word "background" in their description, others as `black` (per [Tab’s Level 4 proposal](https://rawgithub.com/tabatkins/specs/master/css-color/Overview.html#system-colors))
- Something else?

@fantasai, do you have an opinion?

**Comment by flying-sheep** [comment]
note that the deprecation is invalid since the thing it was deprecated in favor of was dropped from the standard: the link is dangling, the `appearance` property is nowhere to be found in any standard.

there already is the special property `Color::CurrentColor`, so we’d just have to add one for every system color and be done with it: let consumers decide what to do with those.

**Comment by jdm** [comment]
To clarify @flying-sheep's comment, they were looking at the TR/ versions of the spec. The `appearance` is specified in http://dev.w3.org/csswg/css-ui-4/#appearance-switching.

**Comment by flying-sheep** [comment]
ahah! CSS level 4, sorry.

well, my proposal still stands: pass them as enum members. maybe provide a convenience function to decide if a color is a background system color or foreground system color to ease using them [like Tab proposed](http://dev.w3.org/csswg/css-color-4/#system-colors)

as the `appearance` property was stripped down to basically “normal” and “button”, the system colors remain useful to allow for a more native look (i don’t want a black-on-gray application in my gray-on-dark-teal system)

**Comment by GPHemsley** [comment]
Looks like the spec has come a long way on these:
https://www.w3.org/TR/css-color-4/#css-system-colors
https://www.w3.org/TR/css-color-4/#deprecated-system-colors
