### ISSUE TITLE
skip_whitespace is inefficient for non-whitespace tokens

### ISSUE THREAD

**Issue by jdm** [servo/rust-cssparser#209]
Depending on how often we call skip_whitespace when non-whitespace tokens are expected (which is actually quite common, IIRC) we can probably make it more efficient by adding a case to the top of the match at https://github.com/servo/rust-cssparser/blob/master/src/tokenizer.rs#L459 that catches any byte after `/` and immediately returns.

**Comment by SimonSapin** [comment]
Line 459 is currently ` b' ' | b'\t' => {`, I don’t understand what you mean by "any byte after `/`".

**Comment by jdm** [comment]
I mean that `/` has the highest ascii value, so any byte value greater than it is clearly not whitespace. Adding a check for that case before any other might be more efficient.

**Comment by SimonSapin** [comment]
Oh I see. So something like `byte if byte > b'/' => return,`  ?

**Comment by jdm** [comment]
Yeah.

**Comment by emilio** [comment]
We use `match_byte` for this now, which uses a lookup table, which seems to perform well
