### ISSUE TITLE
Broken documentation on docs.rs

### ISSUE THREAD

**Issue by RazrFalcon** [servo/rust-cssparser#242]
https://docs.rs/cssparser/0.25.3/cssparser/struct.Parser.html#method.parse_nested_block

Methods doesn't have documentation. But if I run `cargo doc` manually - everything is fine. Not sure if this is `docs.rs` bug or `cssparser` one. Other crates on `docs.rs` have documentations.

**Comment by SimonSapin** [comment]
The docs appear to be "collapsed" by default. Click on `[+]` to expand. I don’t know how rustdoc chooses a default behavior, or how that has changed over time.

**Comment by RazrFalcon** [comment]
Strange. Maybe a `docs.rs` bug.
