### ISSUE TITLE
Selectors 4?

### ISSUE THREAD

**Issue by Boscop** [servo/rust-cssparser#272]
Would it be possible to add support for selectors level 4?
E.g.
`tr:nth-last-child(1 of :not(.table_vert_controls))`
https://www.w3.org/TR/selectors-4/#the-nth-last-child-pseudo

**Comment by SimonSapin** [comment]
This would belong in the `selectors` crate https://github.com/servo/servo/tree/master/components/selectors/, which is used in Servo and Firefox. See also https://bugzilla.mozilla.org/show_bug.cgi?id=854148

**Comment by Boscop** [comment]
@SimonSapin But this crate doesn't seem to depend on the `selectors` crate.
It'd be useful to have support in this crate, because this crate is used in the `scraper` crate.

**Comment by SimonSapin** [comment]
`selectors` depends on `cssparser`, so it can’t also be the other way around. `scraper` can depend on both of them.

Here is an example:

* https://github.com/SimonSapin/victor/blob/fdb11f3e87f6d2d59170d10169fa6deb94e53b94/victor/src/style/rules.rs
* https://github.com/SimonSapin/victor/blob/fdb11f3e87f6d2d59170d10169fa6deb94e53b94/victor/src/style/selectors.rs

**Comment by SimonSapin** [comment]
Closing in favor of https://github.com/servo/servo/issues/26263.
