### ISSUE TITLE
Build error running on Github Actions

### ISSUE THREAD

**Issue by teymour-aldridge** [servo/rust-cssparser#280]
When trying to run on Github Actions (ubuntu-latest), `build.rs` fails to run giving an obtuse exit code. I can't reproduce this locally on my machine so I'm a bit stumped as to what might be causing it.

You can see the output of one such run at: https://github.com/lovelace-ed/lovelace/runs/1747751311

**Comment by emilio** [comment]
This is not actionable at this point. We use github actions for CI now so hopefully whatever was happening isn't reproducible now.
