### ISSUE TITLE
Wrong documentation for `Parser::parse_nested_block`?

### ISSUE THREAD

**Issue by d4h0** [servo/rust-cssparser#281]
Hi,

The docs of [Parser::parse_nested_block](https://docs.rs/cssparser/0.28.1/cssparser/struct.Parser.html#method.parse_nested_block) say at the end:

> The result is overridden to Err(()) if the closure leaves some input before that point.

However, it seems an `UnexpectedToken` error is returned:

```
    ParseError {
        kind: Basic(
            UnexpectedToken(
                Delim(
                    '=',
                ),
            ),
        ),
        location: SourceLocation {
            line: 203,
            column: 6,
        },
    },
```

That also make more sense, I think.

**Comment by d4h0** [comment]
The same is probably true for [parse_entirely](https://docs.rs/cssparser/0.28.1/cssparser/struct.Parser.html#method.parse_entirely), and other methods that say the above.

**Comment by emilio** [comment]
https://github.com/servo/rust-cssparser/pull/372 Fixed this aiui
