### ISSUE TITLE
No way to find out if Token::QuotedString had single or double quotation marks

### ISSUE THREAD

**Issue by snshn** [servo/rust-cssparser#282]
I believe it's crucial for being able to "disassemble" and "re-assemble" CSS back to match the original, 100%.

Basically, `Token::QuotedString(ref value)` should also have `ref double` in it, e.g. `Token::QuotedString(ref value, ref double)`, or something similar.

edit:
if it's possible to use symbols other than `'` and `"` as quotation marks, perhaps it should have `ref symbol` there instead... if the opening and closing marks can be different, likely `ref symbols` (or `ref symbol_open, ref symbol_close`).

**Comment by SimonSapin** [comment]
Correct, it is not goal of this library that parsing then serializing produces the exact same string as any input, only a string that has the same meaning if parsed again. There would be many many cases to consider beyond single v.s. double quotes.

**Comment by snshn** [comment]
Oh, I see. Doesn't break anything for my code base, just thought it was missing from the crate. Thank you a lot for it btw, really works great for my project!
