### ISSUE TITLE
Consider setting up `cargo fmt` check on CI

### ISSUE THREAD

**Issue by zrhoffman** [servo/rust-cssparser#375]
Once #373 is merged and `cargo fmt` produces no diff, `cargo fmt --check` should be added to the CI.

**Comment by emilio** [comment]
Yeah, we should do this. Also cargo clippy perhaps (with relevant ignores if needed), if it doesn't get too annoying.

**Comment by l4l** [comment]
Resolved by https://github.com/servo/rust-cssparser/pull/384?

**Comment by emilio** [comment]
Yes, indeed. Thanks!
