### ISSUE TITLE
Add `serde` optional feature for cssparser-color

### ISSUE THREAD

**Issue by Loirooriol** [servo/rust-cssparser#376]
#363 split the color parsing into a separate crate, which has things like https://github.com/servo/rust-cssparser/blob/c3314d15b281f376538cdc91bbb9ce21d5052231/color/lib.rs#L19

However, its `Cargo.toml` doesn't define any `serde` feature.

@emilio

**Comment by chipnertkj** [comment]
@Loirooriol Hi there, coincidentally I needed the same thing done a while ago, here's my PR: https://github.com/servo/rust-cssparser/pull/377

**Comment by emilio** [comment]
Fixed by #388, thanks @chipnertkj
