### ISSUE TITLE
Latest version `cssparser_color-0.1.0` does not depend on `cssparser-0.34`

### ISSUE THREAD

**Issue by eckz** [servo/rust-cssparser#394]
## Summary

Right now latest version of `cssparser_color` (`0.1.0`) depends on `cssparser-0.33`.

This wouldn't be a massive issue, because I could downgrade the previous version,
 but `selectors` depends on `cssparser-0.34` too, and previous version of `selectors` depends on much older version, making it really difficult to use three crates at the same time.

## How to fix

I think publishing a new version of `cssparser_color` that depends on `cssparser-0.34` should fix the issue.

**Comment by mrobinson** [comment]
@emilio Would you be able to release a new version of `cssparser_color` as well?

**Comment by emilio** [comment]
@mrobinson wanna review https://github.com/servo/rust-cssparser/pull/395? :)

**Comment by emilio** [comment]
Should be fixed now.
