### ISSUE TITLE
RGB values need clamping

### ISSUE THREAD

**Issue by larsbergstrom** [servo/rust-cssparser#76]
Per http://www.w3.org/TR/CSS2/syndata.html#value-def-color, integers and percentages above the maximum should be clamped.

This breaks tests/wpt/css-tests/css21_dev/html4/background-color-088.htm and tests/wpt/css-tests/css21_dev/html4/background-color-089.htm (integers and percentages, respectively).

**Comment by SimonSapin** [comment]
CSS 2 also says this, but the phrasing in CSS Color Level 4 is a bit clearer:

http://dev.w3.org/csswg/css-color/#rgb-functions
> Some devices can output colors technically outside of the sRGB gamut, represented by channels with values less than 0% or greater than 100%. For this reason, values outside of the 0%-100% range are allowed, but are clamped to the device’s gamut.)

My understanding is that since this library doesn’t know the device’s gamut, it shouldn’t be doing the camping.

**Comment by SimonSapin** [comment]
Given that, I’m not sure that these two tests are completely valid, but I don’t feel like arguing with CSSWG about that…

**Comment by SimonSapin** [comment]
@nical, do you know if moz2d supports at all device gamuts other than 0% to 100% for R, G, and B?

**Comment by nical** [comment]
Moz2d doesn't attempt to do anything with device gamut as far as i know, but maybe some of the underlying backends do stuff under the hood I know that at least cairo clamps color values into the [0 - 1] range for instance.

**Comment by SimonSapin** [comment]
Alright, let’s not bother trying to support non-standard gamuts, then.

**Comment by SimonSapin** [comment]
CSS Color Level 4 removed the paragraph quoted above about device gamuts outside of 0%...100%. Now it says to clamp:

https://drafts.csswg.org/css-color/#rgb-functions
> Values outside these ranges are not invalid, but are clamped to the ranges defined here at computed-value time.

(The "ranges defined here" being 0...255 for unitless numbers and 0%...100% for percentages.)
