### ISSUE TITLE
Build with serde support on CI

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-cssparser#86]
Do something similar to https://github.com/servo/rust-cssparser/pull/85#issuecomment-129135752 for every optional features.

**Comment by Mylainos** [comment]
So we should add something like this to `.travis.yml` at line 13 ?
```
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo test --features serde-serialization)
```

**Comment by SimonSapin** [comment]
Indeed! Thanks for reminding me.
